In [6]:
import pandas as pd

In [7]:


df_visit = pd.read_csv("/Users/rajonkar/Documents/MyLearning/Ex_Files_Python_Data_Analysis_Healthcare/Exercise Files/Demo Hospital Outpatient Data Clean_NHC.csv")
df_visit

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration(minutes),Nursing(minutes),Laboratory(minutes),Consultation(minutes),Pharmacy(minutes)
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33.0,105.0,101.0,28.0,112.0
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46.0,75.0,84.0,102.0,36.0
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107.0,81.0,5.0,77.0,36.0
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66.0,31.0,101.0,35.0,92.0
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68.0,55.0,60.0,90.0,104.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68617,2020-06-22,668182,10,Female,Abdominal pain,True,10006,2718.0,90.0,96.0,62.0,92.0,113.0
68618,2020-09-03,484737,7,Male,Abdominal pain,True,10009,2028.0,101.0,76.0,110.0,37.0,14.0
68619,2021-06-16,917198,22,Female,Urinary Tract Infection,True,20008,1212.0,66.0,80.0,15.0,36.0,5.0
68620,2021-09-15,98720,22,Female,Malaria,True,20006,1668.0,9.0,36.0,107.0,87.0,39.0
68621,2019-12-15,251371,5,Male,Malaria,False,10014,1850.0,18.0,74.0,42.0,44.0,7.0

In [ ]:
df_visit.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Visit_Date     1000000 non-null  object
 1   Patient_ID     1000000 non-null  int64
 2   Age            1000000 non-null  int64
 3   Gender         1000000 non-null  object
 4   Diagnosis      1000000 non-null  object
 5   Has_Insurance  1000000 non-null  bool
 6   Postcode       1000000 non-null  int64
 7   Total_Cost     1000000 non-null  float64
 8   Registration   1000000 non-null  int64
 9   Nursing        1000000 non-null  int64
 10  Laboratory     1000000 non-null  int64
 11  Consultation   1000000 non-null  int64
 12  Pharmacy       1000000 non-null  int64
dtypes: bool(1), float64(1), int64(8), object(3)
memory usage: 92.5+ MB

In [ ]:
df_visit.isna()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,False,False,False,False,False,False,False,False,False
999997,False,False,False,False,False,False,False,False,False,False,False,False,False
999998,False,False,False,False,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df_visit.isna().sum()

Visit_Date       0
Patient_ID       0
Age              0
Gender           0
Diagnosis        0
Has_Insurance    0
Postcode         0
Total_Cost       0
Registration     0
Nursing          0
Laboratory       0
Consultation     0
Pharmacy         0
dtype: int64

In [ ]:
df_visit.dropna()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [ ]:
df_visit = df_visit.dropna()
df_visit

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [ ]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [ ]:
df_visit.head(20)

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
5,2022-06-22,47297,14,Male,Ear Infection,True,10004,1464.0,47,103,69,20,5
6,2022-03-30,703464,52,Male,Urinary Tract Infection,False,10013,3410.0,35,79,117,73,37
7,2021-12-19,969327,44,Female,Malaria,False,10001,2130.0,56,36,68,26,27
8,2020-09-16,246521,55,Male,Diabetes,False,20001,3140.0,39,37,95,68,75
9,2022-04-23,796347,68,Female,Diabetes,False,10012,2160.0,28,17,48,111,12
10,2018-02-22,920307,84,Male,Malaria,True,10008,1212.0,40,59,10,19,74
11,2018-11-13,732391,28,Female,Diabetes,True,20013,1830.0,87,23,104,35,56
12,2019-06-20,649246,38,Male,Diabetes,False,10010,3680.0,102,61,80,103,22
13,2021-02-02,173739,75,Male,Malaria,False,20006,3000.0,94,65,86,23,32
14,2019-06-06,683024,22,Male,Backpain,True,20007,2466.0,104,42,69,82,114
15,2019-07-24,483458,45,Female,Hypertension,True,20002,1566.0,108,7,105,11,30
16,2018-03-18,281665,12,Female,Abdominal pain,False,10015,2170.0,61,31,50,12,63
17,2018-05-30,320804,81,Male,Hypertension,False,10006,2010.0,56,58,34,15,38
18,2019-01-09,432976,39,Female,Backpain,False,20006,2070.0,81,31,7,32,56
19,2018-05-13,905564,51,Female,Urinary Tract Infection,False,10009,3760.0,115,32,47,91,91

In [ ]:
df_visit.rename(columns={'Registration': 'Registration_minutes'})

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [ ]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [ ]:
df_visit.rename(columns={'Registration': 'Registration_minutes'},inplace=True)

In [ ]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [ ]:
column_mapping = {'Nursing':'Nursing_minutes','Laboratory': 'Laboratory_minutes','Consultation':'Consulation_minutes','Pharmacy': 'Pharmacy_minutes'}

In [ ]:
df_visit.rename(columns=column_mapping,inplace=True)
df_visit

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consulation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100