In [55]:
import pandas as pd

In [66]:


df_visit = pd.read_csv("/Users/rajonkar/Documents/MyLearning/Ex_Files_Python_Data_Analysis_Healthcare/Exercise Files/Demo Hospital Outpatient Data_NHC.csv")
df_visit

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [57]:
df_visit.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 13 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Visit_Date     1000000 non-null  str
 1   Patient_ID     1000000 non-null  int64
 2   Age            1000000 non-null  int64
 3   Gender         1000000 non-null  str
 4   Diagnosis      1000000 non-null  str
 5   Has_Insurance  1000000 non-null  bool
 6   Postcode       1000000 non-null  int64
 7   Total_Cost     1000000 non-null  float64
 8   Registration   1000000 non-null  int64
 9   Nursing        1000000 non-null  int64
 10  Laboratory     1000000 non-null  int64
 11  Consultation   1000000 non-null  int64
 12  Pharmacy       1000000 non-null  int64
dtypes: bool(1), float64(1), int64(8), str(3)
memory usage: 92.5 MB

In [58]:
df_visit.isna()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,False,False,False,False,False,False,False,False,False,False,False,False,False
999996,False,False,False,False,False,False,False,False,False,False,False,False,False
999997,False,False,False,False,False,False,False,False,False,False,False,False,False
999998,False,False,False,False,False,False,False,False,False,False,False,False,False
999999,False,False,False,False,False,False,False,False,False,False,False,False,False

In [59]:
df_visit.isna().sum()

Visit_Date       0
Patient_ID       0
Age              0
Gender           0
Diagnosis        0
Has_Insurance    0
Postcode         0
Total_Cost       0
Registration     0
Nursing          0
Laboratory       0
Consultation     0
Pharmacy         0
dtype: int64

In [60]:
df_visit.dropna() # defualt drops rows even if a single column has na. control it using how= all or how = any
#how='all': Drops the row or column only if all values in it are missing.
#how='any' (Default): Drops the row or column if at least one missing value is present.

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [ ]:
df_visit = df_visit.dropna()
df_visit

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [ ]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [21]:
df_visit.head(7)

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration(minutes),Nursing(minutes),Laboratory(minutes),Consultation(minutes),Pharmacy(minutes)
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33.0,105.0,101.0,28.0,112.0
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46.0,75.0,84.0,102.0,36.0
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107.0,81.0,5.0,77.0,36.0
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66.0,31.0,101.0,35.0,92.0
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68.0,55.0,60.0,90.0,104.0
5,2022-06-22,47297,14,Male,Ear Infection,True,10004,1464.0,47.0,103.0,69.0,20.0,5.0
6,2022-03-30,703464,52,Male,Urinary Tract Infection,False,10013,3410.0,35.0,79.0,117.0,73.0,37.0

In [61]:
df_visit.rename(columns={'Registration': 'Registration_minutes'})

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [ ]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [62]:
df_visit.rename(columns={'Registration': 'Registration_minutes'},inplace=True)

In [ ]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing,Laboratory,Consultation,Pharmacy
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [63]:
column_mapping = {'Nursing':'Nursing_minutes','Laboratory': 'Laboratory_minutes','Consultation':'Consulation_minutes','Pharmacy': 'Pharmacy_minutes'}

In [64]:
df_visit.rename(columns=column_mapping,inplace=True)
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consulation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104

In [65]:
df_visit

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration_minutes,Nursing_minutes,Laboratory_minutes,Consulation_minutes,Pharmacy_minutes
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33,105,101,28,112
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46,75,84,102,36
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107,81,5,77,36
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66,31,101,35,92
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68,55,60,90,104
...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,2018-09-30,385435,9,Male,Abdominal pain,True,10004,1458.0,80,52,11,42,58
999996,2020-05-08,117261,29,Female,Urinary Tract Infection,True,20009,1836.0,59,57,64,66,60
999997,2019-12-31,594613,39,Female,Upper Respiratory Tract Infection,False,10001,1930.0,10,14,69,14,86
999998,2019-11-04,152179,39,Female,Malaria,False,20006,3950.0,119,52,60,94,70
999999,2019-05-11,370584,76,Female,Malaria,False,20012,3500.0,34,90,29,97,100

In [16]:
import numpy as np
data = {
    'A': [1.0, 2.0, np.nan, 4.0],
    'B': [5.0, np.nan, np.nan, 8.0],
    'C': [9, 10, 11, 12]
}
df = pd.DataFrame(data)

In [ ]:
df

     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12

In [20]:
df.dropna(how="any")

     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

In [36]:
df3=df.rename({"A":"A1"},axis=1)
df4=df.rename(columns={"A":"A1"})

In [ ]:
df3.head()

    A1    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12

In [38]:
df4.head()

    A1    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12