##Wait time Analysis of Patient Visit Demo Dataset Part I

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
path='/Users/rajonkar/Documents/MyLearning/Ex_Files_Python_Data_Analysis_Healthcare/Exercise Files/Demo Hospital Outpatient Data Clean_NHC.csv'
df_visit = pd.read_csv(path)

In [4]:
# df_visit = pd.read_csv('/content/demo_hospital_outpatient_data_clean.zip')
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration(minutes),Nursing(minutes),Laboratory(minutes),Consultation(minutes),Pharmacy(minutes)
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33.0,105.0,101.0,28.0,112.0
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46.0,75.0,84.0,102.0,36.0
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107.0,81.0,5.0,77.0,36.0
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66.0,31.0,101.0,35.0,92.0
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68.0,55.0,60.0,90.0,104.0

In [7]:
df_visit['Total_Time(minutes)'] = df_visit['Registration(minutes)'] + df_visit['Nursing(minutes)'] + df_visit['Laboratory(minutes)'] + df_visit['Consultation(minutes)'] + df_visit['Pharmacy(minutes)']

In [6]:
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration(minutes),Nursing(minutes),Laboratory(minutes),Consultation(minutes),Pharmacy(minutes),Total_Time(minutes)
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33.0,105.0,101.0,28.0,112.0,379.0
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46.0,75.0,84.0,102.0,36.0,343.0
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107.0,81.0,5.0,77.0,36.0,306.0
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66.0,31.0,101.0,35.0,92.0,325.0
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68.0,55.0,60.0,90.0,104.0,377.0

In [8]:
df_visit['Total_Time(hours)'] = df_visit['Total_Time(minutes)'] / 60
df_visit.head()

,Visit_Date,Patient_ID,Age,Gender,Diagnosis,Has_Insurance,Postcode,Total_Cost,Registration(minutes),Nursing(minutes),Laboratory(minutes),Consultation(minutes),Pharmacy(minutes),Total_Time(minutes),Total_Time(hours)
0,2020-05-06,688923,68,Female,Diabetes,True,20006,2274.0,33.0,105.0,101.0,28.0,112.0,379.0,6.316667
1,2018-08-04,886361,62,Female,Urinary Tract Infection,False,20005,3430.0,46.0,75.0,84.0,102.0,36.0,343.0,5.716667
2,2021-04-10,464823,70,Female,Upper Respiratory Tract Infection,True,10003,1836.0,107.0,81.0,5.0,77.0,36.0,306.0,5.100000
3,2021-10-01,655214,8,Female,Upper Respiratory Tract Infection,False,10006,3250.0,66.0,31.0,101.0,35.0,92.0,325.0,5.416667
4,2018-04-30,454666,24,Male,Malaria,True,10006,2262.0,68.0,55.0,60.0,90.0,104.0,377.0,6.283333

In [9]:
average_total_time_in_hours = df_visit['Total_Time(hours)'].mean()
average_total_time_in_hours

np.float64(5.209994608143161)

In [10]:
max_time_department = df_visit[['Consultation(minutes)','Registration(minutes)','Nursing(minutes)','Laboratory(minutes)','Pharmacy(minutes)']].sum().idxmax()

In [11]:
max_time_department

'Registration(minutes)'

In [12]:
df_visit['Registration(minutes)'].max()

np.float64(120.0)

In [10]:
df_visit['Registration(minutes)'].min()

5.0

##Wait time Analysis of Patient Visit Demo Dataset Part II

In [13]:
def department_wait_time_statistics(df, wait_time_column):
    wait_time_minutes = df[wait_time_column]
    wait_time_hours = wait_time_minutes / 60

    min_time = wait_time_hours.min()
    max_time = wait_time_hours.max()
    mean_time = wait_time_hours.mean()
    median_time = wait_time_hours.median()
    std_dev = wait_time_hours.std()

    sentence = f"For the department'{wait_time_column}', wait times range from {min_time:.2f} hours to {max_time:.2f} hours "\
    f"The average wait time is {mean_time:.2f} hours, with a median of {median_time:.2f} hours" \
    f"The standard deviation is {std_dev:.2f} hours"

    return sentence

In [14]:
department_wait_time_statistics(df_visit,'Nursing(minutes)')

"For the department'Nursing(minutes)', wait times range from 0.08 hours to 2.00 hours The average wait time is 1.04 hours, with a median of 1.03 hoursThe standard deviation is 0.56 hours"

In [15]:
department_wait_time_statistics(df_visit,'Nursing(seconds)')

KeyError: 'Nursing(seconds)'

In [16]:
def department_wait_time_statistics(df, department_name):
    if department_name not in df.columns:
        return f"Department '{department_name}' not found in the DataFrame"
    wait_time_minutes = df[department_name]
    wait_time_hours = wait_time_minutes / 60

    min_time = wait_time_hours.min()
    max_time = wait_time_hours.max()
    mean_time = wait_time_hours.mean()
    median_time = wait_time_hours.median()
    std_dev = wait_time_hours.std()

    sentence = f"For the department'{department_name}', wait times range from {min_time:.2f} hours to {max_time:.2f} hours "\
    f"The average wait time is {mean_time:.2f} hours, with a median of {median_time:.2f} hours" \
    f"The standard deviation is {std_dev:.2f} hours"

    return sentence

In [17]:
department_wait_time_statistics(df_visit,'Nursing(seconds)')

"Department 'Nursing(seconds)' not found in the DataFrame"